### ISSUE TITLE
Add an option to easily generate a bookmarklet that sources a hosted JS file

### ISSUE THREAD

**Issue by daveyarwood** [adzerk-oss/boot-bookmarklet#1]
URL-encoded JS compiled from CLJS can easily exceed the 2000-character limit in URLs, making the bookmarklet unusable. A lot of bookmarklets (even vanilla JS ones) just source an external JS file that is hosted somewhere.

It might be nice to add a task option (or perhaps a separate task) to auto-generate a bookmarklet that does this. Maybe you could even compose this with another task that would upload the compiled JS to somewhere like S3 or Dropbox.

The simplest thing would be just a task that takes any number of script URLs and generates a bookmarklet that sources them. It could be as simple as splicing each URL into this ([source](http://code.tutsplus.com/tutorials/create-bookmarklets-the-right-way--net-18154)):

``` javascript
javascript: (function () { 
    var jsCode = document.createElement('script'); 
    jsCode.setAttribute('src', 'http://path/to/external/file.js');                  
  document.body.appendChild(jsCode); 
 }());
```

**Comment by Samstiles** [comment]
:+1:

**Comment by daveyarwood** [comment]
Just added an `external-bookmarklet` task in 0.2.0!
